config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  mount Ckeditor::Engine => '/ckeditor'
  constraints :subdomain => /^admin/ do
    resources :settings
    resources :articles
    get 'tags/:tag', to: 'articles#index', as: :tags, constraints: {subdomain: 'admin'}
    get 'check_image_type_exist' =>"image_types#check_image_type_exist", constraints: {subdomain: 'admin'}
    get 'check_image_name_exist' =>"image_types#check_image_name_exist", constraints: {subdomain: 'admin'}
    resources :cms_content_types do
      resources :cms_contents do
          collection { post :sort }
      end
    end
  end

  constraints :subdomain => /^blog/ do
    root 'posts#index'
    get 'tags/:tag', to: 'posts#index', as: :tag, constraints: {subdomain: 'blog'}
    get 'archives/:year/:month', to: 'posts#index', as: :archives, constraints: {subdomain: 'blog'}
    resources :posts
  end

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register, constraints: {subdomain: 'admin'}
    get 'login', to: 'devise/sessions#new', as: :login, constraints: {subdomain: 'admin'}
  end
  get '', to: 'articles#dashboard', as: :dashboard, constraints: {subdomain: 'admin'}
  get '', to: 'posts#index', constraints: {subdomain: 'blog'}

  resources :users

  match "*path", to: "posts#catch_404", via: :all

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  acts_as_taggable
  extend FriendlyId
  friendly_id :title, use:  [:slugged, :history]
   scope :published, -> { where(is_published: true) }
   scope :recent, -> { order("created_at DESC") }
   validates_presence_of :title, :post, :tag_list

   def self.search(search)
      if search
        where("post iLIKE ? OR title iLIKE ?", "%#{search}%" , "%#{search}%")
      else
        all
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def dashboard
  end

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
    respond_with(@articles)
  end

  def show
    respond_with(@article)
  end

  def new
    @article = Article.new
    respond_with(@article)
  end

  def edit

  end

  def create
    @article = current_user.articles.build(article_params)
    @article.save
    respond_with(@article)
  end

  def update
    @article.update(article_params)
    $fetch_theme_from_db = Article.first.title
    respond_with(@article)
  end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find_by_slug(params[:id])
    end

    def article_params
      params.require(:article).permit(:user_id, :title, :post, :is_published,:tag_list,:meta_description)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, validate: true do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="">
  <%= f.label :tag_list, "Tags (separated by commas)" %><br />
  <%= f.text_field :tag_list,:class => "form light-form" %>
  </div>
  <div class="">
    <%= f.label :title %><br>
    <%= f.text_field :title,:class => "form light-form" %>
  </div>
  <div class="">
    <%= f.label :meta_description %><br>
    <%= f.text_area :meta_description,:class => "form light-form" %>
  </div>
  <div class="">
    <%= f.label :is_published %>&nbsp;&nbsp;
    <%= f.check_box :is_published %>
  </div>
  <div class="">
    <%= f.label :post %><br>
    <%= f.cktext_area :post, :id => 'sometext' %>
  </div>
  <div class="">
    <%= f.submit 'SAVE' ,:class => "btn btn-default-dark col-xs-3 btn-xs"%>
     <% if action_name == "edit" %>
         <%= link_to 'CANCEL', article_path(@article),:class => "btn btn-default-dark col-xs-3 btn-xs",:style => "margin-left:10px;" %>
     <% end %>
  </div>
<% end %>

<script>
$(function() { $('form[data-validate]').validate(); })
</script>

app/views/articles/dashboard.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="" style="padding-top:10px;margin-bottom:0px;">
              Dashboard 
          </h3>
           
          </div>
              <%= render partial: "layouts/shared/flash_msg" %>
      </div>
  </div>
  <!-- /.row -->

app/views/articles/edit.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
             <%= link_to 'Articles', articles_path,:class => " next_arrow",:style => "" %> <%= link_to @article.title, @article,:class => "next_arrow",:style => "" %>  Edit 
           </h3>
          </div>
      </div>
  </div>
  <!-- /.row -->

<div class="post-form clearfix ">

<div id="main-col" class="">
<%= render 'form' %>
</div>
</div>

app/views/articles/index.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
              Articles 
              <%= link_to 'New Article', new_article_path,:class => "pull-right",:style => "" %>
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

  <div class="clearfix ">
      <div id="tag_cloud">
        <% tag_cloud Article.tag_counts, %w[btn btn-default btn-lg] do |tag, css_class| %>
          <%= link_to tag.name, tag_path(tag.name), class: "btn btn-default btn-xs",:style => "padding: 10px 15px;" %>
        <% end %>
      </div><br/>
      <div class="table-responsive">
     <% if @articles.present? %>
        <table class="table table-bordered" id ="pages_table">
        <thead>
          <tr>
            <th >User</th>
            <th>Title</th>
            <th >Tags</th>
            <th >Published</th>
            <th ></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
           <% @articles.each do |article| %>
              <tr>
                <td><%= article.user.present? ? article.user.name : 'No Author' %></td>
                <td><%= article.title %></td>
                <td><%= raw article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></td>
                <td><%= article.is_published %></td>
                <td style="font-weight:bold"><%= link_to 'Preview', article %></td>
                <td style="font-weight:bold"><%= link_to 'Edit', edit_article_path(article) %></td>
                <td style="font-weight:bold"><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
           <% end %>
        </tbody>
      </table>
      <% else %>
            <div class="row text-center">No Articles</div>
         <% end %>
      </div>
      </div>
  <!-- /.row -->

            

<script type="text/javascript">
$(document).ready(function() { 
  var aoColumnDefs = [
        {
            "aTargets": [4,5,6],
            "bSortable": false
        }
    ];
    var dataTable = $('#pages_table').dataTable({
      "iDisplayLength": 10,
      "aoColumnDefs": aoColumnDefs
    });
});
</script>

app/views/articles/new.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
               <%= link_to 'Articles', articles_path,:class => "next_arrow",:style => "" %>New Article
           </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

<div class="post-form clearfix ">
<div id="main-col" class="">
<%= render 'form' %>
</div>
</div>

app/views/articles/show.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
               <%= link_to 'Articles ', articles_path,:class => "next_arrow"  %><%= @article.title%>
              <%= link_to 'Edit', edit_article_path(@article),:class => "pull-right",:style => ""  %>
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

  <div class="clearfix ">
<div id="main-col" class="blog col-xs-12 col-sm-12 col-md-9">
    
    <article class="post">
      <div class="entry-content">
      <div class="post-date-icon">
        <div class="post-icon">
        <i class="fa fa-camera"></i>
        </div>
        <div class="post-date">
        <span class="day"><%= @article.created_at.strftime("%d")%></span>
        <span class="month"><%= @article.created_at.strftime("%b %Y")%></span>
        </div>
      </div>
      <div class="post-details col-md-10">
      <h3><%= @article.title %></h3>
      <footer class="entry-meta">
      <span class="autor-name"><%= @article.user.present? ? @article.user.name : 'No Author' %></span>
      <span class="meta">  <%= raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></span>
      </footer>
      <p><%= raw @article.post %></p>

  <footer class="entry-meta tags">
  <ul class="list-unstyled">
    <li>
      <span class="blog-icons icon-tags"></span>
      <%= raw @article.tag_list.map { |t| link_to t, tag_path(t) }.join(' ') %>
    </li>
  </ul>
  </footer>
  </div>
  </div>
  </article>
  </div>
  </div>