config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  mount Ckeditor::Engine => '/ckeditor'
  constraints :subdomain => /^admin/ do
    resources :settings
    resources :articles
    get 'tags/:tag', to: 'articles#index', as: :tags, constraints: {subdomain: 'admin'}
    get 'check_image_type_exist' =>"image_types#check_image_type_exist", constraints: {subdomain: 'admin'}
    get 'check_image_name_exist' =>"image_types#check_image_name_exist", constraints: {subdomain: 'admin'}
    resources :cms_content_types do
      resources :cms_contents do
          collection { post :sort }
      end
    end
  end

  constraints :subdomain => /^blog/ do
    root 'posts#index'
    get 'tags/:tag', to: 'posts#index', as: :tag, constraints: {subdomain: 'blog'}
    get 'archives/:year/:month', to: 'posts#index', as: :archives, constraints: {subdomain: 'blog'}
    resources :posts
  end

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register, constraints: {subdomain: 'admin'}
    get 'login', to: 'devise/sessions#new', as: :login, constraints: {subdomain: 'admin'}
  end
  get '', to: 'articles#dashboard', as: :dashboard, constraints: {subdomain: 'admin'}
  get '', to: 'posts#index', constraints: {subdomain: 'blog'}

  resources :users

  match "*path", to: "posts#catch_404", via: :all

end

app/controllers/cms_content_types_controller.rb
class CmsContentTypesController < ApplicationController
  before_action :set_cms_content_type, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @cms_content_types = CmsContentType.all
    respond_with(@cms_content_types)
  end

  def show
    respond_with(@cms_content_type)
  end

  def new
    @cms_content_type = CmsContentType.new
    respond_with(@cms_content_type)
  end

  def edit
  end



  def check_image_type_exist
    image_type = params[:fieldValue]
    validate_ajax_except = params[:validate_ajax_except]
    if validate_ajax_except.present?
      @cms_content_type = CmsContentType.where("lower(name) = ?", image_type.downcase).where("id != ?", validate_ajax_except).first
    else
      @cms_content_type = CmsContentType.where("lower(name) = ?", image_type.downcase).first
    end
    if @cms_content_type.present?
      respond_to do |format|
        format.json  { render :json =>{ :brand_exist => false } }
      end
    else
      respond_to do |format|
        format.json  { render :json =>{ :brand_exist => true } }
      end
    end
  end

  def check_image_name_exist
    image_type = params[:fieldValue]
    validate_ajax_except = params[:validate_ajax_except]
    if validate_ajax_except.present?  
      @cms_content_type = CmsContentType.where("lower(image_type) = ?", image_type.downcase).where("id != ?", validate_ajax_except).first
    else
      @cms_content_type = CmsContentType.where("lower(image_type) = ?", image_type.downcase).first
    end
    if @cms_content_type.present?
      respond_to do |format|
        format.json  { render :json =>{ :brand_exist => false } }
      end
    else
      respond_to do |format|
        format.json  { render :json =>{ :brand_exist => true } }
      end
    end
  end

  def create
    @cms_content_type = CmsContentType.new(cms_content_type_params)
    @cms_content_type.save
    respond_with(@cms_content_type)
  end

  def update
    @cms_content_type.update(cms_content_type_params)
    respond_with(@cms_content_type)
  end

  def destroy
    @cms_content_type.destroy
    respond_with(@cms_content_type)
  end

  private
    def set_cms_content_type
      @cms_content_type = CmsContentType.find(params[:id])
    end

    def cms_content_type_params
      params.require(:cms_content_type).permit(:name, :image_type, :height, :width, :is_video)
    end
end

app/helpers/cms_content_types_helper.rb
module CmsContentTypesHelper
end

app/views/cms_content_types/_form.html.erb
<%= form_for(@cms_content_type, validate: true ) do |f| %>
    <div class="">
        <% if @cms_content_type.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@cms_content_type.errors.count, "error") %> prohibited this cms_content_type from being saved:</h2>

            <ul>
            <% @cms_content_type.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="row">
          <div class="col-sm-6 col-xs-6">
            <div class="form-group form_group_admin_image_type_name" style="width:100%">
              <label for="inputError" class="col-xs-12 col-sm-12 col-md-12 control-label no-padding-right label-color" style="padding-bottom:17px;">Name*</label><br /><br/>
                <span class="block input-icon input-icon-right">
                  <%= f.text_field :name,:class => "form light-form",:data => {validate_ajax_url: ''} %>
                </span>
                <div class="help-block" id="admin_image_type_name_error1"> </div>
            </div>
          </div>
          <div class="col-sm-6 col-xs-6">
            <div class="form-group form_group_admin_image_type_image_type" style="width:100%">
              <label for="inputError" class="col-xs-12 col-sm-12 col-md-12 control-label no-padding-right label-color">Media Type*<span style="font-size:10px;">(should be Unique, is used to fetch in view)</span></label><br />
                <span class="block input-icon input-icon-right">
                  <%= f.text_field :image_type,:class => "form light-form",:style => "width:100%",:data => {validate_ajax_url: ''} %>
                </span>
                <div class="help-block" id="admin_image_type_image_type_error1"> </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-xs-6">
            <div class="form-group form_group_admin_image_type_width">
              <label for="inputError" class="col-xs-12 col-sm-12 col-md-12 control-label no-padding-right label-color">Width*</label>
                <span class="block input-icon input-icon-right">
                  <%= f.text_field :width,:class => "form light-form", :placeholder => "In pixel" %>
                </span>
                <div class="help-block" id="admin_image_type_width_error1"> </div>
            </div>
          </div>
          <div class="col-sm-6 col-xs-6">
            <div class="form-group form_group_admin_image_type_height">
              <label for="inputError" class="col-xs-12 col-sm-12 col-md-12 control-label no-padding-right label-color">Height*</label>
                <span class="block input-icon input-icon-right">
                  <%= f.text_field :height,:class => "form light-form", :placeholder => "In pixel" %>
                </span>
                <div class="help-block" id="admin_image_type_height_error1"> </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 col-xs-6">
          </div>
          <div class="col-sm-6 col-xs-6">
            <div class="form-group form_group_admin_image_type_is_video">
              <label for="inputError" class="col-xs-12 col-sm-12 col-md-12 control-label no-padding-right label-color">Is video</label>
              <div class="col-xs-12 col-sm-12">
                <span class="block input-icon input-icon-right">
                  <label>
                    <%= f.check_box :is_video,:class=>"ace" %>
                    <span class="lbl label-color"> </span>
                  </label>
                </span>
                <div class="help-block" id="admin_image_type_is_video_error1"> </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="actions">
        <%= f.submit 'SAVE' ,:class => "btn btn-default-dark col-xs-3 btn-xs"%> 
         <% if action_name == "edit" %>
             <%= link_to 'CANCEL', cms_content_type_path(@cms_content_type),:class => "btn btn-default-dark col-xs-3 btn-xs",:style => "margin-left:10px;" %>
         <% end %>
      </div>
<% end %>

<script>
$(function() { $('form[data-validate]').validate(); })
</script>

app/views/cms_content_types/edit.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
              <%= link_to 'Cms Content Types', cms_content_types_path,:class => "next_arrow"%>
              <%= link_to @cms_content_type.name, cms_content_type_path(@cms_content_type),:class => "next_arrow"%>
              Edit 
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

<div class="post-form clearfix ">
<%= render 'form' %>
</div>

app/views/cms_content_types/index.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;"> 
              Cms Contents Types
              <%= link_to 'New Cms content', new_cms_content_type_path,:class => "pull-right" %>
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

  <div class="clearfix ">

  <% if @cms_content_types.present? %>
        <table class="table table-bordered" id="content_type_table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Image Type (should be Unique, is used to fetch in the View)</th>
            <th>Height</th>
            <th>Width</th>
            <th>Is Video</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
           <% @cms_content_types.each do |cms_content_type| %>
              <tr>
                  <td><%= cms_content_type.name %></td>
                  <td><%= cms_content_type.image_type %></td>
                  <td><%= cms_content_type.height %></td>
                  <td><%= cms_content_type.width %></td>
                    <td><%= cms_content_type.is_video %></td>
                  <td style="font-weight:bold"><%= link_to 'Preview', cms_content_type %></td>
                  <td style="font-weight:bold"><%= link_to 'Edit', edit_cms_content_type_path(cms_content_type)  %></td><td style="font-weight:bold">
                  <% unless cms_content_type.cms_contents.first.present? %>
                  <%= link_to 'Destroy', cms_content_type, method: :delete, data: { confirm: 'Are you sure?' } %>
                  <% end %></td>
              </tr>
           <% end %>
        </tbody>
      </table>
      <% else %>
           <div class="row text-center">No Content Type</div>
     <% end %>
</div>
<br>


<script>
$(document).ready(function(){
  var aoColumnDefs = [
        {
            "aTargets": [5,6,7],
            "bSortable": false
        }
    ];
    var dataTable = $('#content_type_table').dataTable({
      "iDisplayLength": 10,
      "aoColumnDefs": aoColumnDefs
    });
});
</script>

app/views/cms_content_types/new.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
              <%= link_to 'Cms Content Types', cms_content_types_path,:class => "next_arrow"%>
              New Cms Content Type
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

<div class="post-form clearfix ">
<%= render 'form' %>
</div>

app/views/cms_content_types/show.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
               <%= link_to 'Cms Content Types ', cms_content_types_path,:class => "next_arrow"  %> 
               <%= link_to @cms_content_type.name, cms_content_type_path(@cms_content_type)%>
              <%= link_to 'Create Cms Content', new_cms_content_type_cms_content_path(@cms_content_type)  , :class => "for_page_load",:class => "pull-right" %>
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

  <div class="clearfix ">
     <div class="row">
              <div class="col-xs-10 col-sm-10">
                <div id="parent-images-cats" class = "sort_images row" data-update-url="<%= sort_cms_content_type_cms_contents_path(@cms_content_type) %>" style="padding: 20px;">
                  <% @cms_content_type.cms_contents.each do |image| %>
                    <%= content_tag_for(:div, image, :class => "col-sm-2 col-xs-3 img-thumbnail", :style => "margin: 10px;") do %>
                      <i class="ace-icon fa fa-arrows handle" style=""></i>
                      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_cms_content_type_cms_content_path(@cms_content_type,image), :class=>"pull-right" %>
                      <%= link_to '<i class="fa fa-trash"></i>'.html_safe, cms_content_type_cms_content_path(@cms_content_type,image), method: :delete, data: { confirm: 'Are you sure?' },:class => "delete_button_color" %>
                      <%= image_tag image.avatar.url(:thumb),:class=>"" %>

                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
  </div>



<script>
jQuery(function() {
  return $('#parent-images-cats').sortable({
    handle: '.handle',
    update: function() {
      return $.post($(this).data('update-url'), $(this).sortable('serialize'));
    }
  });
});
</script>