config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  mount Ckeditor::Engine => '/ckeditor'
  constraints :subdomain => /^admin/ do
    resources :settings
    resources :articles
    get 'tags/:tag', to: 'articles#index', as: :tags, constraints: {subdomain: 'admin'}
    get 'check_image_type_exist' =>"image_types#check_image_type_exist", constraints: {subdomain: 'admin'}
    get 'check_image_name_exist' =>"image_types#check_image_name_exist", constraints: {subdomain: 'admin'}
    resources :cms_content_types do
      resources :cms_contents do
          collection { post :sort }
      end
    end
  end

  constraints :subdomain => /^blog/ do
    root 'posts#index'
    get 'tags/:tag', to: 'posts#index', as: :tag, constraints: {subdomain: 'blog'}
    get 'archives/:year/:month', to: 'posts#index', as: :archives, constraints: {subdomain: 'blog'}
    resources :posts
  end

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register, constraints: {subdomain: 'admin'}
    get 'login', to: 'devise/sessions#new', as: :login, constraints: {subdomain: 'admin'}
  end
  get '', to: 'articles#dashboard', as: :dashboard, constraints: {subdomain: 'admin'}
  get '', to: 'posts#index', constraints: {subdomain: 'blog'}

  resources :users

  match "*path", to: "posts#catch_404", via: :all

end

app/models/cms_content.rb
class CmsContent < ActiveRecord::Base
    #GEMS USED
  #ACCESSORS
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h, :processing, :deferred_image
  attr_writer :deferred_image
  #ASSOCIATIONS
  has_attached_file :avatar,

  styles: lambda { |a| a.instance.is_image? ? {:large => a.instance.styles,:medium => "300x300!", :thumb => "100x100!"}  : {:thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10}, :medium => { :geometry => "300x300#", :format => 'jpg', :time => 10}}},
  processors: lambda { |a| a.is_video? ? "" : [ :cropper ] }
  belongs_to :cms_content_type, class_name:"CmsContentType"
  #VALIDATIONS
  validates :title, :presence => true
  validates_attachment_content_type :avatar, :content_type => ['application/x-shockwave-flash', 'application/x-shockwave-flash', 'application/flv', 'video/mp4','image/jpeg', 'image/jpg', 'image/png']
  #CALLBACKS
  after_update :reprocess_avatar, :if => :cropping?
  after_create :update_sort_order
  after_save :assign_deferred_image
  before_save :link_validation
  #SCOPES
  #CUSTOM SCOPES
  #OTHER METHODS

  def update_sort_order
     @sort_maximum= CmsContent.maximum("sort_order") ? CmsContent.maximum("sort_order") : 0
      @sort_maximum+=1
      self.sort_order=@sort_maximum
      self.save
  end

  def validate_image_size
    if avatar.file? && avatar.size > get_current_file_size_limit
      errors.add_to_base(" ... Your error message")
    end
  end 

  def styles
    if self.cms_content_type.present?
      return "#{self.cms_content_type.width}x#{self.cms_content_type.height}!"
    else
      return "1000x1000!"
    end
  end

  def is_image?
    [ 'image/jpeg', 
      'image/jpg',
      'image/png' ].include?(avatar.content_type)
  end

  def is_video?
    [ 'application/x-mp4',
      'video/mp4',
      'video/mpeg',
      'video/quicktime',
      'video/x-la-asf',
      'video/x-ms-asf',
      'video/x-msvideo',
      'video/x-sgi-movie',
      'video/x-flv',
      'flv-application/octet-stream',
      'video/3gpp',
      'video/3gpp2',
      'video/3gpp-tt',
      'video/BMPEG',
      'video/BT656',
      'video/CelB',
      'video/DV',
      'video/H261',
      'video/H263',
      'video/H263-1998',
      'video/H263-2000',
      'video/H264',
      'video/JPEG',
      'video/MJ2',
      'video/MP1S',
      'video/MP2P',
      'video/MP2T',
      'video/mp4',
      'video/MP4V-ES',
      'video/MPV',
      'video/mpeg4',
      'video/mpeg4-generic',
      'video/nv',
      'video/parityfec',
      'video/pointer',
      'video/raw',
      'video/rtx' ].include?(avatar.content_type)
  end

  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end


  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end

  #JOBS
  #PRIVATE 

  def reprocess_avatar
    return unless (cropping? && !processing)
    self.processing = true
    avatar.reprocess!
    self.processing = false
  end

  def assign_deferred_image
    if @deferred_image
      self.avatar = @deferred_image
      @deferred_image = nil
      save!
    end
  end
  
  def link_validation
    if self.link.match("https://").present?
    elsif self.link.match("http://").present?
    else
      self.link = "http://" + self.link
    end
  end
end

app/models/cms_content_type.rb
class CmsContentType < ActiveRecord::Base
    #GEMS USED
  #ACCESSORS
  #ASSOCIATIONS
  has_many :cms_contents, class_name:"CmsContent"
  #VALIDATIONS
  validates :name, :presence => true, :uniqueness => true
   validates :image_type, :presence => true, :uniqueness => true
  validates :width, :presence => true
  validates :height, :presence => true
  #CALLBACKS
  before_save :downcase_fields
  #SCOPES
  #CUSTOM SCOPES
  #OTHER METHODS
  #JOBS
  #PRIVATE 
  def downcase_fields
    self.name.downcase!
    self.image_type.downcase!
  end
end

app/controllers/cms_contents_controller.rb
class CmsContentsController < ApplicationController
  before_action :set_cms_content, only: [:show, :edit, :update, :destroy]
  before_action :set_cms_content_type

  respond_to :html

  def index
    @cms_contents = CmsContent.all
    respond_with(@cms_contents)
  end

  def show
    respond_with(@cms_content)
  end

  def new
    @cms_content = CmsContent.new
    respond_with(@cms_content)
  end

  def edit
    render :template => "cms_contents/edit"
  end

  def create
     cms_content_type = @cms_content_type
    @cms_content = @cms_content_type.cms_contents.build(cms_content_params)
    if @cms_content.save
      if params[:cms_content][:avatar].blank?
        flash[:notice] = "Cms content was successfully created."
        redirect_to @cms_content
      else
        render :action => "crop"
      end
    else
      render :template => "cms_contents/new"
    end

  end


  def sort
    params[:cms_content].each_with_index do |id, index|
      CmsContent.where(id: id).update_all(sort_order: index+1)
    end
    render nothing: true
  end

  def update

    if @cms_content.update(cms_content_params)

      if params[:cms_content][:avatar].blank?
        if params[:cms_content][:crop_x].present?
          flash[:notice] = "Cms content was successfully updated."
          redirect_to @cms_content_type
        else
          render :action => "crop"
        end
      else
        render :action => "crop"
      end
    else
      format.html { render :edit }
      format.json { render json: @cms_content.errors, status: :unprocessable_entity }
    end

  end


  def destroy
    @cms_content.destroy
    redirect_to @cms_content_type
  end

  private

    def set_cms_content_type
      @cms_content_type = CmsContentType.find(params[:cms_content_type_id])
    end

    def set_cms_content
      @cms_content = CmsContent.find(params[:id])
    end 

    def cms_content_params
      params.require(:cms_content).permit(:title, :link,:avatar,:description, :image_type_id, :category_id, :alt_text, :crop_x, :crop_y, :crop_w, :crop_h)
    end
end

app/helpers/cms_contents_helper.rb
module CmsContentsHelper
end

app/views/cms_contents/_form.html.erb
<%= form_for(@cms_content, :url => cms_content_type_cms_contents_path(@cms_content_type), validate: true ) do |f| %>
  <% if @cms_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cms_content.errors.count, "error") %> prohibited this cms_content from being saved:</h2>

      <ul>
      <% @cms_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

       <div class="form-horizontal">
        <div class="">
          <div class="row">
            <div class="col-sm-12 col-xs-12">
            <div class="col-sm-6 col-xs-12">
            <% if @cms_content_type.is_video %>
              <div class="form-group form_group_admin_general_image_avatar row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2 control-label no-padding-right label-color">Video</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right">
                    <%= f.file_field :avatar,:class => "" %>
                  </span>
                  <div class="help-block" id="admin_avatar_error1"> </div>
                </div>
              </div>
            <% else %>
              <div class="form-group form_group_admin_general_image_avatar row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2  no-padding-right label-color">Image</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right" style="padding-top:8px;">
                   <% if f.object.avatar.present? %>
                    <%= image_tag f.object.avatar.url(:thumb),:class => "img-thumbnail" %>
                    <% end %>
                    <%= f.file_field :avatar,:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_avatar_error1"> </div>
                </div>
               
              </div>
            <% end %>
            </div>

              <div class="col-sm-6 col-xs-12">
            <div class="form-group form_group_admin_general_image_ait_text row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2  no-padding-right label-color">Title</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right">
                    <%= f.text_field :title,:placeholder => "Link",:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_general_image_title_error1"> </div>
                </div>
              </div>
              </div>
            <div class="col-sm-6 col-xs-12">
             <div class="form-group form_group_admin_general_image_link">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2 control-label no-padding-right label-color" style="text-align:left;">Link*</label>
                <div class="col-xs-12 col-sm-8">
                  <div class="input-group">
                    <span class="input-group-addon">
                      https://
                    </span>
                    <span class="block input-icon input-icon-right">
                    <%= f.text_field :link, :class => "blue_textbox form-control   width-100 validate_this", :id => "page_link", :placeholder => "Example : www.example.com" ,:style => "width:107.5%"%>
                    </span>
                  </div>
                  <div class="help-block" id="admin_general_image_link_error1"> </div>
                </div>
               
              </div>
       
              </div>
            <div class="col-sm-6 col-xs-12">
            <div class="form-group form_group_admin_general_image_ait_text row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2  no-padding-right label-color">AltText</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right">
                    <%= f.text_field :alt_text,:placeholder => "Alt text",:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_general_image_alt_text_error1"> </div>
                </div>
              </div>
              </div>
            <div class="col-sm-12 col-xs-12">
            <div class="form-group form_group_admin_general_image_ait_text row">
                <label for="inputError" class="col-xs-12 col-sm-12 col-md-12  no-padding-right label-color">Description</label>
                <div class="col-xs-1 col-sm-1"></div>
                <div class="col-xs-12 col-sm-10">
                  <span class="block input-icon input-icon-right">
                    <%= f.cktext_area :description, :id => 'sometext' ,:placeholder => "Description",:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_general_image_description_error1"> </div>
                </div>
              </div>
              </div>
            <div class="row">
              <div class="col-xs-12 col-sm-10">
                <%= f.submit "Save", :class => "btn btn-default-dark col-xs-3 btn-xs" %>
               <% if action_name == "edit" %>
                   <%= link_to 'CANCEL', cms_content_type_path(@cms_content_type),:class => "btn btn-default-dark col-xs-3 btn-xs",:style => "margin-left:10px;" %>
               <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>
<script>
$(function() { $('form[data-validate]').validate(); })
</script>

app/views/cms_contents/crop.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="" style="padding-top:10px;margin-bottom:0px;">
              Cms Contents 
          </h3>
          <h3 class="" style="padding-top:10px;margin-bottom:0px;">
          </h3>
           
          </div>
      </div>
  </div>
  <!-- /.row -->

  <div class="clearfix ">
  <% content_for(:head) do %>
  <script type="text/javascript" charset="utf-8">
  $(function() {
    $('#cropbox').Jcrop({
      onChange: update_crop,
      onSelect: update_crop,
      setSelect: [0, 0, 100, 100],
      aspectRatio: 0
    });
  });
  function update_crop(coords) {
    var rx = 100/coords.w;
    var ry = 100/coords.h;
    $('#preview').css({
      width: Math.round(rx * <%= @cms_content.avatar_geometry(:large).width %>) + 'px',
      height: Math.round(ry * <%= @cms_content.avatar_geometry(:large).height %>) + 'px',
      marginLeft: '-' + Math.round(rx * coords.x) + 'px',
      marginTop: '-' + Math.round(ry * coords.y) + 'px'
    });
    var ratio = <%= @cms_content.avatar_geometry(:original).width %> / <%= @cms_content.avatar_geometry(:large).width %>;
    $("#crop_x").val(Math.round(coords.x * ratio));
    $("#crop_y").val(Math.round(coords.y * ratio));
    $("#crop_w").val(Math.round(coords.w * ratio));
    $("#crop_h").val(Math.round(coords.h * ratio));
  }
  </script>
  <% end %>

  <%= image_tag @cms_content.avatar.url(:large), :id => "cropbox" %>

  <h4>Preview:</h4>
  <div style="width:100px; height:100px; overflow:hidden">
    <%= image_tag @cms_content.avatar.url(:large), :id => "preview",:remote => true %>
  </div>
  <%= form_for @cms_content,:url => cms_content_type_cms_content_path(@cms_content_type,@cms_content) do |f| %>
    <% for attribute in [:crop_x, :crop_y, :crop_w, :crop_h] %>
      <%= f.hidden_field attribute, :id => attribute %>
    <% end %><br />
    <p><%= f.submit "Crop", :class => "btn btn-default btn-xs" %></p>
  <% end %>
</div>

app/views/cms_contents/edit.html.erb
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">

          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
              <%= link_to 'Cms Content Types', cms_content_types_path,:class => "next_arrow"%>
              <%= link_to @cms_content_type.name, cms_content_type_path(@cms_content_type),:class => "next_arrow"%>
              Edit <%= @cms_content.title %>
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

<div class="post-form clearfix ">
<%= form_for(@cms_content, :url => cms_content_type_cms_content_path(@cms_content_type,@cms_content), validate: true ) do |f| %>
  <% if @cms_content.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cms_content.errors.count, "error") %> prohibited this cms_content from being saved:</h2>

      <ul>
      <% @cms_content.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <div class="form-horizontal">
        <div class="">
          <div class="row">
            <div class="col-sm-12 col-xs-12">
            <div class="col-sm-6 col-xs-12">
            <% if @cms_content_type.is_video %>
              <div class="form-group form_group_admin_general_image_avatar row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2 control-label no-padding-right label-color">Video</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right">
                    <%= f.file_field :avatar,:class => "" %>
                  </span>
                  <div class="help-block" id="admin_avatar_error1"> </div>
                </div>
              </div>
            <% else %>
              <div class="form-group form_group_admin_general_image_avatar row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2  no-padding-right label-color">Image</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right" style="padding-top:8px;">
                   <% if f.object.avatar.present? %>
                    <%= image_tag f.object.avatar.url(:thumb),:class => "img-thumbnail" %>
                    <% end %>
                    <%= f.file_field :avatar,:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_avatar_error1"> </div>
                </div>
               
              </div>
            <% end %>
            </div>

              <div class="col-sm-6 col-xs-12">
            <div class="form-group form_group_admin_general_image_ait_text row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2  no-padding-right label-color">Title</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right">
                    <%= f.text_field :title,:placeholder => "Link",:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_general_image_title_error1"> </div>
                </div>
              </div>
              </div>
            <div class="col-sm-6 col-xs-12">
             <div class="form-group form_group_admin_general_image_link">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2 control-label no-padding-right label-color" style="text-align:left;">Link*</label>
                <div class="col-xs-12 col-sm-8">
                  <div class="input-group">
                    <span class="input-group-addon">
                      https://
                    </span>
                    <span class="block input-icon input-icon-right">
                    <%= f.text_field :link, :class => "blue_textbox form-control   width-100 validate_this", :id => "page_link", :placeholder => "Example : www.example.com" ,:style => "width:107.5%"%>
                    </span>
                  </div>
                  <div class="help-block" id="admin_general_image_link_error1"> </div>
                </div>
               
              </div>
       
              </div>
            <div class="col-sm-6 col-xs-12">
            <div class="form-group form_group_admin_general_image_ait_text row">
                <label for="inputError" class="col-xs-12 col-sm-2 col-md-2  no-padding-right label-color">AltText</label>
                <div class="col-xs-12 col-sm-8">
                  <span class="block input-icon input-icon-right">
                    <%= f.text_field :alt_text,:placeholder => "Alt text",:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_general_image_alt_text_error1"> </div>
                </div>
              </div>
              </div>
            <div class="col-sm-12 col-xs-12">
            <div class="form-group form_group_admin_general_image_ait_text row">
                <label for="inputError" class="col-xs-12 col-sm-12 col-md-12  no-padding-right label-color">Description</label>
                <div class="col-xs-1 col-sm-1"></div>
                <div class="col-xs-12 col-sm-10">
                  <span class="block input-icon input-icon-right">
                    <%= f.cktext_area :description, :id => 'sometext' ,:placeholder => "Description",:class => "form light-form" %>
                  </span>
                  <div class="help-block" id="admin_general_image_description_error1"> </div>
                </div>
              </div>
              </div>
            <div class="row">
              <div class="col-xs-12 col-sm-10">
                <%= f.submit "Save", :class => "btn btn-default-dark col-xs-3 btn-xs" %>
                
               <% if action_name == "edit" %>
                   <%= link_to 'CANCEL', cms_content_type_path(@cms_content_type),:class => "btn btn-default-dark col-xs-3 btn-xs",:style => "margin-left:10px;" %>
               <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>

</div>

<script>
$(function() { $('form[data-validate]').validate(); })
</script>

app/views/cms_contents/index.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          <h3 class="" style="padding-top:10px;margin-bottom:0px;">
              Cms Contents 
              <%= link_to 'New Cms content', new_cms_content_path,:class => "pull-right",:style => "font-size:12px;" %>
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

  <div class="clearfix ">
    <% if  @cms_contents.present?  %>
      <div class="table-responsive">

          <table>
            <thead>
              <tr>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @cms_contents.each do |cms_content| %>
                <tr>
                  <td><%= link_to 'Show', cms_content %></td>
                  <td><%= link_to 'Edit', edit_cms_content_path(cms_content) %></td>
                  <td><%= link_to 'Destroy', cms_content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
  </div>


<br>

app/views/cms_contents/new.html.erb
<!-- Page Heading -->
  <div class="row">
      <div class="col-lg-12">
        <div class="page-header">
          
          <h3 class="breadcrumb_title" style="padding-top:10px;margin-bottom:0px;">
              <%= link_to 'Cms Content Types', cms_content_types_path,:class => "next_arrow"%>
              <%= link_to @cms_content_type.name, cms_content_type_path(@cms_content_type),:class => "next_arrow"%>
              New Cms Content 
          </h3>
          
          </div>
      </div>
  </div>
  <!-- /.row -->

<div class="post-form clearfix ">
<%= render 'form' %>
</div>

app/views/cms_contents/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cms_content_path(@cms_content) %> |
<%= link_to 'Back', cms_contents_path %>