config/routes.rb
Rails.application.routes.draw do

  resources :subscribers

  mount Ckeditor::Engine => '/ckeditor'
  constraints :subdomain => /^admin/ do
    resources :settings
    resources :articles
    get 'tags/:tag', to: 'articles#index', as: :tags, constraints: {subdomain: 'admin'}
    get 'check_image_type_exist' =>"image_types#check_image_type_exist", constraints: {subdomain: 'admin'}
    get 'check_image_name_exist' =>"image_types#check_image_name_exist", constraints: {subdomain: 'admin'}
    resources :cms_content_types do
      resources :cms_contents do
          collection { post :sort }
      end
    end
  end

  constraints :subdomain => /^blog/ do
    root 'posts#index'
    get 'tags/:tag', to: 'posts#index', as: :tag, constraints: {subdomain: 'blog'}
    get 'archives/:year/:month', to: 'posts#index', as: :archives, constraints: {subdomain: 'blog'}
    resources :posts
  end

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register, constraints: {subdomain: 'admin'}
    get 'login', to: 'devise/sessions#new', as: :login, constraints: {subdomain: 'admin'}
  end
  get '', to: 'articles#dashboard', as: :dashboard, constraints: {subdomain: 'admin'}
  get '', to: 'posts#index', constraints: {subdomain: 'blog'}

  resources :users

  match "*path", to: "posts#catch_404", via: :all

end

app/views/layouts/application.html.erb
<% @setting = Setting.first %>
<!DOCTYPE html>
<html>
<head>
   <title><%= yield(:title )|| "Blog"%></title>   
  <meta name="description" content="<%= yield(:meta_description) ||  "Blog" %>"> 
    <%  if @setting.present? %>
        <%= favicon_link_tag @setting.favicon.url(:medium) %>
      <% else %>
          <%= favicon_link_tag 'favicon.ico' %>
      <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
      <%= yield(:head) %>
      <% if request.domain == "coderabbits.com" %>
           <script type="text/javascript" charset="utf-8">
              (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

                ga('create', 'UA-70136221-1', 'auto');
                ga('send', 'pageview');
          </script>
      <% end %>
</head>
<% if controller_name == "confirmations" || controller_name == "sessions" || ( controller_name == "registrations" && (action_name == "new" || action_name == "create") ) || controller_name == "passwords"  %>
<body style="background-image: url(/assets/blog_texture.jpg);background-size:100%">
<% else %>
<body>
<% end %>
  <% if request.subdomain == "admin" %>
      <% if user_signed_in? %>
           <div id="wrapper">
               <!-- Navigation -->
               <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                  <!-- Brand and toggle get grouped for better mobile display -->
                  <div class="navbar-header">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                      </button>
                       <a class="navbar-brand" href="http://www.coderabbits.com/"><span style="color:white;font-size:13px;">BLOG ADMIN</span>  <%= image_tag 'coderabbits_white_logo.png',:style=>"width:122px;margin-top: -1.7px;" %></a> 
                  </div>
                  <!-- Top Menu Items -->
                  <ul class="nav navbar-right top-nav">
                      <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.name %>&nbsp;<b class="caret"></b></a>
                          <ul class="dropdown-menu">
                              <li>
                                  <a href="<%= edit_user_registration_path %>"><i class="fa fa-fw fa-user"></i> Profile</a>
                              </li>
                              <li>
                                  <a href="<%= settings_path %>"><i class="fa fa-fw fa-gear"></i> Settings</a>
                              </li>
                              <li class="divider"></li>
                              <li>
                                  <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
                              </li>
                          </ul>
                      </li>
                  </ul>
                  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
                  <div class="collapse navbar-collapse navbar-ex1-collapse">
                      <ul class="nav navbar-nav side-nav">
                              
                          <li class="<%= controller_name == 'articles' && action_name == 'dashboard' ? 'active' : nil %>">
                              <%= link_to "<i class='fa fa-fw fa-dashboard'></i> &nbsp;Dashboard ".html_safe, dashboard_path%> 
                          </li>
                          <li class="<%= controller_name == 'articles' && action_name != 'dashboard' ? 'active' : nil %>">
                              <%= link_to "<i class='fa fa-fw fa-font'></i> &nbsp;Articles ".html_safe, articles_path,:remote => false%> 
                          </li>
                          <li class="<%= controller_name == 'cms_contents' ? 'active' : nil %>">
                              <%= link_to "<i class='fa fa-file-word-o'></i> &nbsp;Cms Content Type ".html_safe, cms_content_types_path %> 
                          </li>
                          <li class="<%= controller_name == 'users' ? 'active' : nil %>">
                              <%= link_to "<i class='fa fa-fw fa-users'></i> &nbsp;Users ".html_safe, users_path%> 
                          </li>
                          <li class="<%= controller_name == 'subscribers' ? 'active' : nil %>">
                              <%= link_to "<i class='fa fa-fw fa-user-plus'></i> &nbsp;Subscribers ".html_safe, subscribers_path %> 
                          </li>
                          <li class="<%= controller_name == 'settings' ? 'active' : nil %>">
                              <%= link_to "<i class='fa fa-fw fa-cog'></i> &nbsp;Settings ".html_safe, settings_path %> 
                          </li>
                      </ul>
                  </div>
                <!-- /.navbar-collapse -->
               </nav>
               <div id="page-wrapper">
                  <div class="container-fluid">
                    <%= yield %>
                   </div>
                <!-- /.container-fluid -->
               </div>
               <!-- /#page-wrapper -->
        </div>
         <footer class="" style="height:30px;position:fixed;bottom:0px;background:white;paddin-bottom:20px;padding-top:10px;">
              <div class="container">
                  <div class="">

                      <div class=" col-sm-12 col-xs-12 col-lg-5 col-md-5 hidden-xs hidden-sm" style="font-weight:bold;padding-left:7%;"> </div>
                       <div class="text-center col-sm-12 col-xs-12 col-lg-4 col-md-4" style="font-weight:bold;padding-left:10.1%;padding-right:0px;">Copyright © Coderabbits. All Rights Reserved.</div>
                  </div>
              </div>
           </footer>
      <% else %>
            <%= yield %>

            <style>
            .form-signin, .form-signin1{
              max-width: 400px; 
              display:block;
              background-color: #FFF;
              -moz-box-shadow: 0 0 3px 3px #888;
                -webkit-box-shadow: 0 0 3px 3px #888;
              box-shadow: 0 0 3px 3px #ADB1B0;
            }
            .main{
              padding: 38px;
            }
            .social-box{
              margin: 0 auto;
              padding: 38px;
              border-bottom:1px #ccc solid;
            }
            .social-box a{
              font-weight:bold;
              font-size:18px;
              padding:8px;
            }
            .social-box a i{
              font-weight:bold;
              font-size:20px;
            }
            .heading-desc{
              font-size: 20px;
              font-weight: bold;
              padding: 38px 38px 0px 38px;
              background: #f0f0f0;
              margin: 0 auto;
              border-bottom: 1px solid #dadada;
              padding: 20px;
              text-align: center;
              color:#666666 !important;
              
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox, .form-signin1 .form-signin-heading,
            .form-signin1 .checkbox{
              margin-bottom: 10px;
            }
            .form-signin .checkbox,.form-signin1 .checkbox {
              font-weight: normal;
            }
            .form-signin .form-control,.form-signin1 .form-control {
              position: relative;
              font-size: 16px;
              height: 20px;
              padding: 20px;
            }
            .form-control{
                  display: block;
                    width: 100%;
                    height: 34px;
                    padding: 6px 12px;
                    font-size: 14px;
                    line-height: 1.42857143;
                    color: #555;
                    background-color: #fff;
                    background-image: none;
                    border: 1px solid #ccc;
                    border-radius: 0px;
                    -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
                    box-shadow: inset 0 1px 1px rgba(0,0,0,0.075);
                    -webkit-transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
                    transition: border-color ease-in-out .15s, box-shadow ease-in-out .15s;
            }
            .form-signin .form-control:focus,.form-signin1 .form-control:focus {
              z-index: 2;
            }
            .form-signin input[type="text"],.form-signin1 input[type="email"],.form-signin1 input[type="text"],.form-signin1 input[type="email"] {
              margin-bottom: 10px;
              
            }
            .form-signin input[type="password"],.form-signin1 input[type="password"] {
              margin-bottom: 10px;
            }
            .login-footer{
              background:#f0f0f0;
              margin: 0 auto;
              border-top: 1px solid #dadada;
              padding:20px;
            }
            .login-footer .left-section a{
              font-weight:bold;
              color:#8a8a8a;
              line-height:19px;
            }
            .mg-btm{
              margin-bottom:20px;
            }
            .form-control{
               border-radius: 0px !important;
            }
            input[type="text"], input[type="email"],input[type="password"] {
                -moz-box-sizing: border-box;
                font-size: 16px;
                height: 50% !important;
                width: 100%;
                padding:10px 20px !important;
            }
            </style>
            <footer class="" style="height:20px;position:fixed;bottom:20px;color:white">
              <div class="container">
                  <div class="">
                      <div class=" col-sm-12 col-xs-12 col-lg-4 col-md-4 hidden-xs hidden-sm" style="padding-left:7%;"> Powered by <a href="http://www.coderabbits.com">CODERABBITS</a></div>
                       <div class="text-center col-sm-12 col-xs-12 col-lg-4 col-md-4 hidden-xs hidden-sm"  style="font-weight:bold;padding-left:10%">Blog Admin <br/><%= image_tag 'coderabbits_white_logo.png',:style=>"width:120px" %></div>
                       <div class="text-center col-sm-12 col-xs-12 col-lg-4 col-md-4" style="padding-left:10.1%;padding-right:0px;">Copyright © Coderabbits. All Rights Reserved.</div>
                  </div>
              </div>
           </footer>
        <% end %>
      <% else %>
            <%= render find_header_type("header") %>
            <%= render "posts/breadcrumb" %>
             <div class="container">
                   <%= render partial: "layouts/shared/flash_msg" %> 
                   <div class="row">
                          <div id="main-col" class="blog col-xs-12 col-sm-12 col-md-9">
                                <%= yield %>
                           </div>
                          <%= render "sidebar" %>
                    </div>
             </div>
             <%= render find_header_type("footer") %>
      <% end %>
</body>
</html>